In [53]:
import pandas as pd
import numpy as np
import urllib.request
import cv2

raw_data = pd.read_table("https://raw.githubusercontent.com/vashineyu/slides_and_others/master/tutorial/examples/imagenet_urls_examples.txt", header= None)
raw_data.columns=["ID","URL"]
print(raw_data)

                  ID                                                URL
0      n00015388_157  http://farm1.static.flickr.com/145/430300483_2...
1      n00015388_238  http://farm2.static.flickr.com/1005/3352960681...
2      n00015388_304  http://farm1.static.flickr.com/27/51009336_a96...
3      n00015388_327  http://farm4.static.flickr.com/3025/2444687979...
4      n00015388_355  http://img100.imageshack.us/img100/3253/forres...
...              ...                                                ...
9990  n00433802_5197  http://grfx.cstv.com/photos/schools/afa/sports...
9991  n00433802_5202  http://farm2.static.flickr.com/1130/960179413_...
9992  n00433802_5204  http://static.flickr.com/150/387324732_f8149d0...
9993  n00433802_5208  http://3.bp.blogspot.com/_9T2cRtlgHV0/SK55RHay...
9994  n00433802_5211  http://www.loudoungymnastics.com/images/Girls_...

[9995 rows x 2 columns]


In [56]:
for i in range(5):
    req = urllib.request.urlopen(raw_data['URL'][i])
    image = np.asarray(bytearray(req.read()), dtype="uint8")
    image = cv2.imdecode(image, cv2.IMREAD_COLOR)
    print(image)

[[[150 110  81]
  [148 110  78]
  [145 111  75]
  ...
  [171 132  88]
  [171 132  88]
  [171 131  89]]

 [[150 110  81]
  [148 110  78]
  [145 110  76]
  ...
  [170 131  86]
  [170 131  87]
  [170 130  88]]

 [[149 110  78]
  [147 109  77]
  [144 108  78]
  ...
  [170 131  86]
  [170 131  87]
  [170 130  88]]

 ...

 [[ 87  88  84]
  [ 86  87  83]
  [ 85  88  86]
  ...
  [ 84  81  73]
  [ 84  80  75]
  [ 84  79  76]]

 [[ 86  87  83]
  [ 85  86  82]
  [ 84  87  85]
  ...
  [ 84  81  73]
  [ 84  80  75]
  [ 84  79  76]]

 [[ 86  87  83]
  [ 85  86  84]
  [ 82  85  83]
  ...
  [ 84  81  73]
  [ 84  80  75]
  [ 84  79  76]]]
[[[ 77  90  98]
  [ 77  90  98]
  [ 85  99 105]
  ...
  [ 30  41  45]
  [ 32  42  49]
  [ 33  43  50]]

 [[ 80  93 101]
  [ 77  90  98]
  [ 83  97 103]
  ...
  [ 32  43  47]
  [ 34  44  51]
  [ 36  46  53]]

 [[ 77  90  98]
  [ 73  87  93]
  [ 79  93  99]
  ...
  [ 31  42  46]
  [ 33  43  50]
  [ 34  44  51]]

 ...

 [[ 68 100 119]
  [ 65  97 116]
  [ 59  91 110]
  ..

HTTPError: HTTP Error 404: Not Found